export const gengo: string;
export const gengoContainer: string;
export const gengoContainerStarted: string;
export const gengoName: string;
export const gengoNameFlip: string;
export const gengoNameFinish: string;
export const gengoYear: string;
export const gengoYearFlip: string;
export const gengoYearFinish: string;
